// Package sqlgen 提供企业级 SQL 代码生成工具库
// 支持多数据库 Schema 解析和类型安全的代码生成
package sqlgen

// DatabaseType 表示数据库类型
type DatabaseType string

const (
	// DatabaseMySQL MySQL 数据库
	DatabaseMySQL DatabaseType = "mysql"
	// DatabasePostgres PostgreSQL 数据库
	DatabasePostgres DatabaseType = "postgres"
	// DatabaseSQLite SQLite 数据库
	DatabaseSQLite DatabaseType = "sqlite"
)

// NamingRule 表示命名规则
type NamingRule string

const (
	// NamingSnakeCase 蛇形命名法 (user_name)
	NamingSnakeCase NamingRule = "snake_case"
	// NamingCamelCase 驼峰命名法 (userName)
	NamingCamelCase NamingRule = "camel_case"
	// NamingPascalCase 帕斯卡命名法 (UserName)
	NamingPascalCase NamingRule = "pascal_case"
)

// 默认配置值
const (
	// DefaultOutputDir 默认输出目录
	DefaultOutputDir = "./generated"
	// DefaultPackageName 默认包名
	DefaultPackageName = "models"
	// DefaultSoftDeleteField 默认软删除字段名
	DefaultSoftDeleteField = "deleted_at"
	// DefaultCreatedAtField 默认创建时间字段名
	DefaultCreatedAtField = "created_at"
	// DefaultUpdatedAtField 默认更新时间字段名
	DefaultUpdatedAtField = "updated_at"
	// DefaultVersionField 默认版本字段名
	DefaultVersionField = "version"
)

// 代码生成标记
const (
	// GeneratedFileHeader 生成文件头部注释
	GeneratedFileHeader = "// Code generated by sqlgen. DO NOT EDIT."
	// UserCodeBegin 用户代码开始标记
	UserCodeBegin = "// BEGIN USER CODE"
	// UserCodeEnd 用户代码结束标记
	UserCodeEnd = "// END USER CODE"
)
